name: iamhere_backend
description: Backend API на Shelf с PostgreSQL
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.3
  postgres: ^3.5.7
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^3.0.0

